"""init

Revision ID: 4acdd785401a
Revises: 
Create Date: 2025-12-08 01:44:02.841680

"""
from typing import Sequence, Union
import src

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4acdd785401a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failure_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institution_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('engineer', 'manager', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spare_part_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('institution_type_id', sa.Integer(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['institution_type_id'], ['institution_type.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spare_part',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('spare_part_category_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spare_part_category_id'], ['spare_part_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('installed', src.models.StringToDate(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('equipment_model_id', sa.Integer(), nullable=True),
    sa.Column('equipment_category_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_category_id'], ['equipment_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipment_model_id'], ['equipment_model.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_model_spare_part',
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('equipment_model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_model_id'], ['equipment_model.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_part.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spare_part_id', 'equipment_model_id')
    )
    op.create_table('spare_part_location_quantity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('spare_part_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_part.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('engineer', 'manager', name='role'), nullable=False),
    sa.Column('workplace_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('hire_at', sa.Date(), nullable=False),
    sa.Column('receive_low_stock_notification', sa.Boolean(), nullable=False),
    sa.Column('receive_repair_request_created_notification', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workplace_id'], ['institution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('repair_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('urgency_level', sa.Enum('critical', 'non_critical', name='urgencylevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('manager_note', sa.String(), nullable=True),
    sa.Column('engineer_note', sa.String(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_scope',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scope.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'scope_id')
    )
    op.create_table('failure_type_repair_request',
    sa.Column('repair_request_id', sa.Integer(), nullable=False),
    sa.Column('failure_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['failure_type_id'], ['failure_type.id'], ),
    sa.ForeignKeyConstraint(['repair_request_id'], ['repair_request.id'], ),
    sa.PrimaryKeyConstraint('repair_request_id', 'failure_type_id')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('repair_request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repair_request_id'], ['repair_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_request_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'not_taken', 'waiting_spare_parts', 'finished', name='repairrequeststatus'), nullable=False),
    sa.Column('responsible_user_id', sa.Integer(), nullable=True),
    sa.Column('repair_request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repair_request_id'], ['repair_request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spare_part_repair_request',
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('repair_request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repair_request_id'], ['repair_request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_part.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spare_part_id', 'repair_request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spare_part_repair_request')
    op.drop_table('repair_request_state')
    op.drop_table('file')
    op.drop_table('failure_type_repair_request')
    op.drop_table('user_scope')
    op.drop_table('repair_request')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('spare_part_location_quantity')
    op.drop_table('equipment_model_spare_part')
    op.drop_table('equipment')
    op.drop_table('spare_part')
    op.drop_table('institution')
    op.drop_table('supplier')
    op.drop_table('spare_part_category')
    op.drop_table('scope')
    op.drop_table('manufacturer')
    op.drop_table('institution_type')
    op.drop_table('failure_type')
    op.drop_table('equipment_model')
    op.drop_table('equipment_category')
    # ### end Alembic commands ###
